"""added budget,, will_fly, description to trip.

Revision ID: 4e3c80337214
Revises: 94ffb6e04923
Create Date: 2023-08-20 22:57:57.138103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3c80337214'
down_revision = '94ffb6e04923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('will_fly', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('will_fly')
        batch_op.drop_column('budget')

    # ### end Alembic commands ###
